name: se
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Charting
  fl_chart: ^0.68.0

  # Advanced Features
  csv: ^6.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true